import { Router } from "express";

import accountRouter from "./accounts.routes";
import attendanceRouter from "./attendance.routes";
import authRouter from "./auth.routes";
import billRouter from "./bill.routes";
import contractRouter from "./contract.routes";
import equipmentRouter from "./equipment.routes";
import invoiceRouter from "./invoice.routes";
import leaveAllocateRouter from "./leaveAllocate.routes";
import leaveRouter from "./leave.routes";
import materialReconciliationRouter from "./materialReconciliation.routes";
import materialRouter from "./material.routes";
import milestoneRouter from "./milestone.routes";
import reimbursementRouter from "./reimbursement.routes";
import payrollRouter from "./payroll.routes";
import procurementRouter from "./procurement.routes";
import projectRouter from "./project.routes";
import quotationRouter from "./quotation.routes";
import siteRouter from "./site.routes";
import tenderRouter from "./tender.routes";
import tdsRouter from "./tds.routes";
import userRouter from "./user.routes";
import vendorRouter from "./vendor.routes";
import voucherRouter from "./voucher.routes";
import workRouter from "./work.routes";

const indexRouter = Router();

indexRouter.use("/auth", authRouter);
indexRouter.use("/accounts", accountRouter);
indexRouter.use("/attendance-logs", attendanceRouter);
indexRouter.use("/users", userRouter);
indexRouter.use("/projects", projectRouter);
indexRouter.use("/bills", billRouter);
indexRouter.use("/contracts", contractRouter);
indexRouter.use("/equipments", equipmentRouter);
indexRouter.use("/invoices", invoiceRouter);
indexRouter.use("/leaves", leaveRouter);
indexRouter.use("/leave-allocations", leaveAllocateRouter);
indexRouter.use("/procurements", procurementRouter);
indexRouter.use("/quotations", quotationRouter);
indexRouter.use("/material-reconciliations", materialReconciliationRouter);
indexRouter.use("/materials", materialRouter);
indexRouter.use("/tenders", tenderRouter);
indexRouter.use("/tds", tdsRouter);
indexRouter.use("/vendors", vendorRouter);
indexRouter.use("/vouchers", voucherRouter);
indexRouter.use("/sites", siteRouter);
indexRouter.use("/works", workRouter);
indexRouter.use("/milestones", milestoneRouter);
indexRouter.use("/reimbursements", reimbursementRouter);
indexRouter.use("/payrolls", payrollRouter);

export default indexRouter;
