export const SEED_ADMIN_USER = {
  name: "Admin",
  email: "admin@crm.com",
  rawPassword: "admin123",
  department: "Admin",
  roleId: 0,
  designation: "Administrator",
  dateOfJoining: "2024-01-01",
  sallery: 150000,
  type: "employee" as const,
  pancardNo: "ADMIN001",
  aadharNo: "999999999999",
  pancardUrl: "https://example.com/pancard/admin",
  aadharUrl: "https://example.com/aadhar/admin",
  pfDeduction: true,
  esiDeduction: true,
  adminId: 1,
  uanNumber: "UAN001",
  age: 35,
} as const;
